Updates to Deployment types table
rishky-msft/Moodle pull request #1
Opened 2022-12-06 05:11 UTC by saikondapalli11

Ran few updates on Deploymen types table

2022-12-06 05:44 UTC, rishky-msft requested changes

2022-12-06 05:44 UTC, rishky-msft commented on README.md
> +| Minimal  | This deployment will use NFS, Azure Database for MySQL Flexible Server, and smaller autoscale web frontend VM sku (1 core) that'll give faster deployment time (less than 30 minutes) and
Do we want to mention the sku type along with vCores.
For example in maximal we are using memory optimized and in other we are using General purpose?

2022-12-06 05:44 UTC, rishky-msft commented on README.md
>  NOTE: Depending on the region you choose to deploy the stack in - the deployment might fail due to SKUs being hardcoded in the template where they are not available. For example, today our small-mid-
Are these reference for Gen-4 for MySQL is still valid for Flexible server?

2022-12-06 05:45 UTC, rishky-msft commented on README.md
There are few other reference in this readme for MySQL single server. Can we replace it with Flexible Server.

For example :  Line no 45

2022-12-06 22:56 UTC, saikondapalli11 commented on README.md
Line number 45 points to the main landing page of Azure Database for MySQL, it talks about the service but does not define whether it's single or flexible server, so we can leave that line as it is now.

2022-12-06 23:38 UTC, saikondapalli11 commented on README.md
>  NOTE: Depending on the region you choose to deploy the stack in - the deployment might fail due to SKUs being hardcoded in the template where they are not available. For example, today our small-mid-
Not really, I will remove this statement, because we support v4 in every region and v5 where possible, at the moment I see all our predefined templates using v4

2022-12-07 00:32 UTC, saikondapalli11 commented on README.md
> +| Minimal  | This deployment will use NFS, Azure Database for MySQL Flexible Server, and smaller autoscale web frontend VM sku (1 core) that'll give faster deployment time (less than 30 minutes) and
I have added that information as well, review once you are online.

2022-12-07 05:04 UTC, rishky-msft approved these changes
LGTM

2022-12-07 05:05 UTC, merged